// src/lib/products-data.ts
import type { Product } from '@/types/products'

export const products: Product[] = [
  // ─────────── Caps & Enclosures ───────────
  {
    id: '1',
    slug: '28mm-cap',
    name: '28 mm Cap',
    industries: ['others'],
    tagline: 'Standard white threaded cap for containers and closures.',
    shortDescription: 'Injection‑moulded PP cap with precise threading.',
    description:
      'This 28 mm cap is a versatile closure used in packaging and container applications across appliance and industrial sectors.',
    applications: ['Household containers', 'Industrial packaging'],
    keyProperties: [
      { label: 'Material', value: 'Polypropylene', unit: '' },
      { label: 'Weight', value: '2.5', unit: 'g' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [
      {
        type: 'datasheet',
        title: '28mm Cap Datasheet',
        fileSizeLabel: 'PDF · 180 KB',
        href: '#',
      },
    ],
    faq: [
      {
        question: 'What colours are available?',
        answer: 'Standard white. Custom colours available on request.',
      },
    ],
    relatedProductSlugs: ['38mm-cap'],
    images: { card: '/assets/products/28mm.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '2',
    slug: '38mm-cap',
    name: '38 mm Cap',
    industries: ['others'],
    tagline: 'Widely used cap for industrial and consumer containers.',
    shortDescription: 'Durable PP cap with consistent diameter and wall thickness.',
    description:
      '38 mm cap suitable for larger container openings, produced with high‑repeatability injection moulding.',
    applications: ['Large household containers', 'Chemical drums'],
    keyProperties: [
      { label: 'Material', value: 'Polypropylene', unit: '' },
      { label: 'Weight', value: '4.1', unit: 'g' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: ['28mm-cap'],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '3',
    slug: '28mm-dish-cap',
    name: '28 mm Dish Cap',
    industries: ['others'],
    tagline: 'Specialised cap with dish profile for unique designs.',
    shortDescription: 'Low‑profile cap for cosmetic and speciality packaging.',
    description:
      'The dish cap provides a sleek, low‑profile closure often required in premium product packaging.',
    applications: ['Cosmetic packaging', 'Speciality containers'],
    keyProperties: [{ label: 'Material', value: 'PP', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/28mm_dish_cap.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '4',
    slug: '89mm-cap',
    name: '89 mm Cap',
    industries: ['others'],
    tagline: 'Wide red cap for large‑format containers.',
    shortDescription: 'High‑visibility industrial cap for bulk packaging.',
    description:
      'Engineered for durability and ease of handling on large industrial containers.',
    applications: ['Bulk chemical drums', 'Large storage containers'],
    keyProperties: [
      { label: 'Material', value: 'PP', unit: '' },
      { label: 'Diameter', value: '89', unit: 'mm' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/89mm2.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '5',
    slug: '67mm-cap',
    name: '67 mm Cap',
    industries: ['others'],
    tagline: 'Red cap for medium‑sized containers.',
    shortDescription: 'Reliable seal for jars and bottles up to 67 mm.',
    description:
      'High‑volume production with consistent colour and dimensions.',
    applications: ['Jars', 'Industrial bottles'],
    keyProperties: [{ label: 'Colour', value: 'Red', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Toro & Ditch Witch Parts (Automotive) ───────────
  {
    id: '6',
    slug: 'seat-bottom',
    name: 'Seat Bottom',
    industries: ['automotive'],
    tagline: 'Large structural seat for off‑road utility vehicles.',
    shortDescription: 'Injection‑moulded seat base for Toro vehicles.',
    description:
      'Heavy‑duty part designed to withstand vibration and outdoor exposure. Exported to the United States.',
    applications: ['Toro Workman', 'Ditch Witch vehicles'],
    keyProperties: [
      { label: 'Weight', value: '3.2', unit: 'kg' },
      { label: 'Material', value: 'PP‑GF30', unit: '' },
    ],
    technicalSpecs: [
      {
        title: 'Mechanical',
        specs: [
          {
            property: 'Tensile Strength',
            value: '85',
            unit: 'MPa',
            standard: 'ISO 527',
          },
        ],
      },
    ],
    certifications: ['IATF 16949'],
    downloads: [
      {
        type: 'datasheet',
        title: 'Seat Bottom TDS',
        fileSizeLabel: 'PDF · 240 KB',
        href: '#',
      },
    ],
    faq: [],
    relatedProductSlugs: ['control-mechanism'],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '7',
    slug: 'vac-handle',
    name: 'Vac Handle',
    industries: ['automotive', 'others'],
    tagline: 'Ergonomic grip handle for vacuum systems.',
    shortDescription: 'Lightweight moulded handle for commercial vacuums.',
    description:
      'Designed for repetitive use in commercial environments.',
    applications: ['Industrial vacuums', 'Vehicle cleaning systems'],
    keyProperties: [{ label: 'Material', value: 'ABS', unit: '' }],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Toro Optimus Parts (Automotive) ───────────
  {
    id: '8',
    slug: 'button-stop',
    name: 'Button Stop',
    industries: ['automotive'],
    tagline: 'Emergency stop button for autonomous mowers.',
    shortDescription: 'Red safety button component for Toro Optimus.',
    description: 'Critical safety component, exported to the US.',
    applications: ['Autonomous lawnmower'],
    keyProperties: [{ label: 'Colour', value: 'Red', unit: '' }],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '9',
    slug: 'shroud-body-lid',
    name: 'Shroud Body Lid',
    industries: ['automotive'],
    tagline: 'Large grey cover for the Optimus chassis.',
    shortDescription: 'Protective top cover for internal components.',
    description:
      'Precision‑moulded for perfect fit and weather resistance.',
    applications: ['Lawnmower chassis'],
    keyProperties: [{ label: 'Material', value: 'ABS‑PC', unit: '' }],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/shroud_body_lid.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '10',
    slug: 'panel-rear-charger',
    name: 'Panel Rear Charger',
    industries: ['automotive'],
    tagline: 'Rear charging station panel.',
    shortDescription: 'Enclosure for electrical contacts and mounting.',
    description: 'Designed for outdoor durability and easy assembly.',
    applications: ['Charging dock'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '11',
    slug: 'panel-front-charger',
    name: 'Panel Front Charger',
    industries: ['automotive'],
    tagline: 'Angled front panel for charging dock.',
    shortDescription: 'Routes cables and protects connectors.',
    description:
      'Injection‑moulded with precise cut‑outs and mounting bosses.',
    applications: ['Charging station'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '12',
    slug: 'base-charger',
    name: 'Base Charger',
    industries: ['automotive'],
    tagline: 'Mounting base for charging system.',
    shortDescription: 'Structural platform for the charger assembly.',
    description:
      'Supports mechanical loads and provides electrical insulation.',
    applications: ['Charging base'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '13',
    slug: 'chassis-top-cover',
    name: 'Chassis Top Cover',
    industries: ['automotive'],
    tagline: 'Upper shell for drivetrain and electronics.',
    shortDescription: 'Complex grey structural cover.',
    description:
      'High‑quality surface finish and dimensional accuracy required.',
    applications: ['Lawnmower body'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '14',
    slug: 'jl-side-cover',
    name: 'JL Side Cover',
    industries: ['automotive'],
    tagline: 'Durable side cover panel for vehicle exteriors.',
    shortDescription: 'Precision‑moulded side cover for automotive body applications.',
    description:
      'Designed for easy assembly and a clean, finished look, this JL side cover provides durable protection for automotive exterior body panels. Manufactured to IATF 16949 standards.',
    applications: ['Automotive exterior', 'Vehicle body panels'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/jl_side_cover.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '15',
    slug: 'outer-bumper',
    name: 'Outer Bumper',
    industries: ['automotive'],
    tagline: 'Curved impact‑absorbing bumper.',
    shortDescription: 'Protects the mower body during operation.',
    description:
      'Made from high‑impact polymer to withstand repeated low‑speed impacts.',
    applications: ['Lawnmower bumper'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '16',
    slug: 'seat-top',
    name: 'Seat Top',
    industries: ['automotive'],
    tagline: 'Large structural seat top for off‑road utility vehicles.',
    shortDescription: 'Injection‑moulded seat top for Toro vehicles.',
    description:
      'Heavy‑duty seat top designed to withstand vibration and outdoor exposure. Exported to the United States.',
    applications: ['Toro Workman', 'Ditch Witch vehicles'],
    keyProperties: [
      { label: 'Weight', value: '3.2', unit: 'kg' },
      { label: 'Material', value: 'PP‑GF30', unit: '' },
    ],
    technicalSpecs: [
      {
        title: 'Mechanical',
        specs: [
          {
            property: 'Tensile Strength',
            value: '85',
            unit: 'MPa',
            standard: 'ISO 527',
          },
        ],
      },
    ],
    certifications: ['IATF 16949'],
    downloads: [
      {
        type: 'datasheet',
        title: 'Seat Top TDS',
        fileSizeLabel: 'PDF · 240 KB',
        href: '#',
      },
    ],
    faq: [],
    relatedProductSlugs: ['control-mechanism'],
    images: { card: '/assets/products/seat_top.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '17',
    slug: 'avenger-assembly',
    name: 'Avenger Assembly',
    industries: ['automotive'],
    tagline: 'Complete polymer assembly for Avenger platform.',
    shortDescription: 'Ready‑to‑install assembly for Avenger vehicles.',
    description:
      'Injection‑moulded assembly for the Avenger vehicle platform. Manufactured to IATF 16949 standards with full traceability.',
    applications: ['Avenger vehicle platform', 'Automotive systems'],
    keyProperties: [
      { label: 'Assembly Type', value: 'Multi‑component', unit: '' },
    ],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/avenger_assembly.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '18',
    slug: 'k3-assembly',
    name: 'K3 Assembly',
    industries: ['automotive'],
    tagline: 'Multi‑component assembly for K3 platform.',
    shortDescription: 'Complete polymer assembly for K3 vehicle systems.',
    description:
      'Multi‑part polymer assembly manufactured for the K3 platform. Combines structural and functional components into a single ready‑to‑install unit.',
    applications: ['K3 vehicle platform', 'Automotive sub‑assemblies'],
    keyProperties: [
      { label: 'Assembly Type', value: 'Multi‑component', unit: '' },
    ],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/k3_assembly.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '19',
    slug: 'jl-top-cover',
    name: 'JL Top Cover',
    industries: ['automotive'],
    tagline: 'Protective top cover for JL vehicle platform.',
    shortDescription: 'Durable moulded cover for JL chassis components.',
    description:
      'Injection‑moulded top cover designed for the JL vehicle platform. Provides weather resistance and structural protection for internal components.',
    applications: ['JL vehicle chassis', 'Off‑road utility vehicles'],
    keyProperties: [
      { label: 'Material', value: 'PP‑GF', unit: '' },
    ],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/jl_top_cover.png', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Furniture ───────────
  {
    id: '20',
    slug: 'star-base',
    name: 'Star Base',
    industries: ['furniture'],
    tagline: 'Five‑star swivel base for office chairs.',
    shortDescription: 'Sturdy injection‑moulded star base.',
    description:
      'Load‑bearing base component compatible with standard chair mechanisms.',
    applications: ['Office chairs', 'Task seating'],
    keyProperties: [{ label: 'Material', value: 'PP‑GF', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/star-base.jpeg', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '21',
    slug: 'shell-membrane',
    name: 'Shell Membrane',
    industries: ['furniture'],
    tagline: 'Flexible seat shell support.',
    shortDescription: 'Ergonomic membrane for seat comfort.',
    description:
      'Injection‑moulded component providing tensioned support in ergonomic chairs.',
    applications: ['Ergonomic seating', 'Mesh chairs'],
    keyProperties: [{ label: 'Material', value: 'TPE', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/shell_membrane.jpeg', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '22',
    slug: 'arm-rest',
    name: 'Arm Rest',
    industries: ['furniture'],
    tagline: 'Adjustable arm support for chairs.',
    shortDescription: 'Moulded armrest with soft‑touch surface.',
    description:
      'Available in various colours and surface finishes for comfort and durability.',
    applications: ['Office chairs', 'Lounge seating'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '23',
    slug: 'outer-sleve',
    name: 'Outer Sleve',
    industries: ['furniture'],
    tagline: 'Decorative outer cover for gas lift.',
    shortDescription: 'Telescopic cover tube.',
    description:
      'Used to conceal the height adjustment cylinder in office chairs.',
    applications: ['Chair gas lift cover'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '24',
    slug: 'height-adjuster',
    name: 'Height Adjuster',
    industries: ['furniture'],
    tagline: 'Actuator mechanism for seat height.',
    shortDescription: 'Lever or paddle for gas lift control.',
    description:
      'Ergonomically designed for easy reach and operation.',
    applications: ['Office chairs', 'Bar stools'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '25',
    slug: 'sr-jr-back-rest',
    name: 'Sr./Jr. Back Rest',
    industries: ['furniture'],
    tagline: 'Backrest frames for different chair sizes.',
    shortDescription: 'Sturdy moulded frame for back cushion mounting.',
    description:
      'Senior and Junior variants accommodate different chair dimensions.',
    applications: ['Office chairs', 'Task seating'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '26',
    slug: 'sr-jr-back-cover',
    name: 'Sr./Jr. Back Cover',
    industries: ['furniture'],
    tagline: 'Rear shell cover for backrest.',
    shortDescription: 'Aesthetic cover panel.',
    description:
      'Snaps onto the backrest frame to provide a finished look.',
    applications: ['Chair exterior'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '27',
    slug: 'cub-chair',
    name: 'Cub Chair',
    industries: ['furniture'],
    tagline: 'Compact moulded chair shell.',
    shortDescription: 'Single‑piece chair for educational and home use.',
    description:
      'Lightweight and stackable design, suitable for kids and casual seating.',
    applications: ['Schools', 'Home office'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Appliances ───────────
  {
    id: '28',
    slug: 'base-stand',
    name: 'Base Stand',
    industries: ['appliances'],
    tagline: 'Support stand for household appliances.',
    shortDescription: 'Stable base for mixers, grinders, and similar devices.',
    description:
      'Injection‑moulded with vibration damping and non‑slip feet.',
    applications: ['Kitchen appliances', 'Home electronics'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/base_stand.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '29',
    slug: 'tmbm-duct-cover',
    name: 'TMBM Duct Cover',
    industries: ['appliances'],
    tagline: 'Cover panel for appliance ductwork.',
    shortDescription: 'Thermoplastic duct cover for air management.',
    description:
      'Used in HVAC and domestic appliances to direct airflow safely.',
    applications: ['Air conditioners', 'Dryers'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/tmbm_duct_cover.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '30',
    slug: 'veg-box',
    name: 'Veg Box',
    industries: ['appliances'],
    tagline: 'Refrigerator vegetable crisper tray.',
    shortDescription: 'Clear or opaque storage compartment for produce.',
    description:
      'Designed to maintain optimal humidity and easy cleaning.',
    applications: ['Refrigerators', 'Coolers'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/veg_box.jpeg', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Additional Caps ───────────
  {
    id: '31',
    slug: '79mm-jar-cap',
    name: '79 mm Jar Cap',
    industries: ['others'],
    tagline: 'Large jar cap for wide‑mouth containers.',
    shortDescription: 'Durable cap for jars and wide‑neck bottles.',
    description:
      '79 mm jar cap designed for wide‑mouth jars, providing a secure seal and easy opening. Suitable for food and industrial packaging.',
    applications: ['Food jars', 'Industrial containers'],
    keyProperties: [
      { label: 'Material', value: 'PP', unit: '' },
      { label: 'Diameter', value: '79', unit: 'mm' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '32',
    slug: '70mm-short-cap',
    name: '70 mm Short Cap',
    industries: ['others'],
    tagline: 'Short‑profile cap for low‑height closures.',
    shortDescription: 'Low‑profile cap for compact packaging.',
    description:
      '70 mm short cap with a low profile, ideal for packaging where height is a constraint. Offers reliable sealing performance.',
    applications: ['Compact containers', 'Speciality packaging'],
    keyProperties: [
      { label: 'Material', value: 'PP', unit: '' },
      { label: 'Diameter', value: '70', unit: 'mm' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
]

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByIndustry(industry: string): Product[] {
  if (industry === 'all') return products
  return products.filter((p) => p.industries.includes(industry))
}