// // import type { ProductDetail } from '@/types/products'

// // // ⚠ AWAITING CLIENT DATA — Replace all placeholder values before launch
// // export const products: ProductDetail[] = [
// //   {
// //     id: '1',
// //     slug: 'pp-homopolymer-compound',
// //     name: 'PP Homopolymer Compound',
// //     category: 'thermoplastics',
// //     tagline: 'High-crystallinity homopolymer for rigid industrial packaging and automotive interior components.',
// //     shortDescription: 'High-flow homopolymer polypropylene for injection moulding applications requiring stiffness and processability.',
// //     description: 'A high-crystallinity polypropylene homopolymer compound engineered for rigid packaging and automotive interior applications. This grade offers excellent stiffness, good processability on standard injection moulding equipment, and consistent lot-to-lot quality under IATF 16949 quality systems.',
// //     industries: ['automotive', 'packaging', 'industrial'],
// //     applications: [
// //       'Automotive interior trims and door panels',
// //       'Rigid packaging containers and caps',
// //       'Industrial crates and pallets',
// //       'Appliance housings and structural components',
// //     ],
// //     keyProperties: [
// //       { label: 'Melt Flow Index', value: '12', unit: 'g/10 min' },
// //       { label: 'Density', value: '0.905', unit: 'g/cm³' },
// //       { label: 'Tensile Strength', value: '32', unit: 'MPa' },
// //       { label: 'Flexural Modulus', value: '1450', unit: 'MPa' },
// //     ],
// //     technicalSpecs: [
// //       {
// //         title: 'Physical Properties',
// //         specs: [
// //           { property: 'Density', value: '0.905', unit: 'g/cm³', standard: 'ISO 1183' },
// //           { property: 'Melt Flow Index (230°C/2.16kg)', value: '12', unit: 'g/10 min', standard: 'ISO 1133' },
// //           { property: 'Mould Shrinkage', value: '1.2–1.6', unit: '%', standard: 'ISO 294-4' },
// //         ],
// //       },
// //       {
// //         title: 'Mechanical Properties',
// //         specs: [
// //           { property: 'Tensile Strength at Yield', value: '32', unit: 'MPa', standard: 'ISO 527-2' },
// //           { property: 'Elongation at Yield', value: '8', unit: '%', standard: 'ISO 527-2' },
// //           { property: 'Flexural Modulus', value: '1450', unit: 'MPa', standard: 'ISO 178' },
// //           { property: 'Izod Impact Strength (23°C)', value: '3.5', unit: 'kJ/m²', standard: 'ISO 180' },
// //         ],
// //       },
// //       {
// //         title: 'Thermal Properties',
// //         specs: [
// //           { property: 'Heat Deflection Temperature (0.45 MPa)', value: '95', unit: '°C', standard: 'ISO 75-2' },
// //           { property: 'Vicat Softening Temperature', value: '152', unit: '°C', standard: 'ISO 306' },
// //         ],
// //       },
// //     ],
// //     certifications: ['IATF 16949', 'ISO 9001'],
// //     downloads: [
// //       { type: 'datasheet', title: 'Technical Data Sheet — PP Homopolymer Compound', filename: 'pp-homopolymer-tds.pdf', fileSizeLabel: 'PDF · 420 KB', href: '/assets/downloads/pp-homopolymer-tds.pdf' },
// //       { type: 'sds', title: 'Safety Data Sheet — PP Homopolymer Compound', filename: 'pp-homopolymer-sds.pdf', fileSizeLabel: 'PDF · 280 KB', href: '/assets/downloads/pp-homopolymer-sds.pdf' },
// //     ],
// //     faq: [
// //       { question: 'What is the minimum order quantity?', answer: 'Our standard minimum order quantity is 500 kg for this grade. For trial or sampling quantities, please contact our technical sales team — we accommodate smaller volumes for qualification purposes.' },
// //       { question: 'Is this product suitable for food contact applications?', answer: 'This homopolymer grade can be formulated for food contact compliance upon request. Please specify your regulatory requirements (FDA, EU 10/2011, etc.) when inquiring so we can confirm the appropriate formulation.' },
// //       { question: 'What is the typical lead time for bulk orders?', answer: 'Standard lead time is 2–3 weeks from order confirmation for quantities up to 5 MT. Larger orders may require 4–6 weeks depending on current production scheduling.' },
// //     ],
// //     relatedProductSlugs: ['abs-pc-blend', 'custom-masterbatch'],
// //     images: { card: '', hero: '', gallery: [] },
// //     featured: true,
// //     inStock: true,
// //     metaTitle: 'PP Homopolymer Compound — Thermoplastics | Atharva Polymers',
// //     metaDescription: 'High-crystallinity PP homopolymer compound for rigid packaging and automotive interiors. IATF 16949 certified. Manufactured at MIDC Ranjangaon, Pune.',
// //   },
// //   {
// //     id: '2',
// //     slug: 'abs-pc-blend',
// //     name: 'ABS-PC Engineering Blend',
// //     category: 'engineering-polymers',
// //     tagline: 'High-impact engineering blend for automotive exterior and electronic housing applications.',
// //     shortDescription: 'ABS-PC blend offering excellent impact resistance and heat stability for demanding engineering applications.',
// //     description: 'An engineered ABS-PC (Acrylonitrile Butadiene Styrene – Polycarbonate) blend designed for applications requiring high impact resistance combined with good heat deflection performance. This grade is suitable for automotive exterior components, electronic equipment housings, and consumer durable goods.',
// //     industries: ['automotive', 'consumer-goods', 'industrial'],
// //     applications: [
// //       'Automotive exterior trim and mirror housings',
// //       'Electronic equipment enclosures',
// //       'Consumer appliance structural parts',
// //       'Power tool housings',
// //     ],
// //     keyProperties: [
// //       { label: 'Melt Flow Index', value: '18', unit: 'g/10 min' },
// //       { label: 'Density', value: '1.12', unit: 'g/cm³' },
// //       { label: 'Izod Impact', value: '45', unit: 'kJ/m²' },
// //       { label: 'HDT (0.45 MPa)', value: '118', unit: '°C' },
// //     ],
// //     technicalSpecs: [
// //       {
// //         title: 'Physical Properties',
// //         specs: [
// //           { property: 'Density', value: '1.12', unit: 'g/cm³', standard: 'ISO 1183' },
// //           { property: 'Melt Flow Index (260°C/5kg)', value: '18', unit: 'g/10 min', standard: 'ISO 1133' },
// //         ],
// //       },
// //       {
// //         title: 'Mechanical Properties',
// //         specs: [
// //           { property: 'Tensile Strength at Yield', value: '52', unit: 'MPa', standard: 'ISO 527-2' },
// //           { property: 'Flexural Modulus', value: '2300', unit: 'MPa', standard: 'ISO 178' },
// //           { property: 'Izod Impact Strength (23°C)', value: '45', unit: 'kJ/m²', standard: 'ISO 180' },
// //         ],
// //       },
// //       {
// //         title: 'Thermal Properties',
// //         specs: [
// //           { property: 'Heat Deflection Temperature (0.45 MPa)', value: '118', unit: '°C', standard: 'ISO 75-2' },
// //         ],
// //       },
// //     ],
// //     certifications: ['IATF 16949', 'ISO 9001', 'ISO 14001'],
// //     downloads: [
// //       { type: 'datasheet', title: 'Technical Data Sheet — ABS-PC Blend', filename: 'abs-pc-blend-tds.pdf', fileSizeLabel: 'PDF · 380 KB', href: '/assets/downloads/abs-pc-blend-tds.pdf' },
// //     ],
// //     faq: [
// //       { question: 'Can this grade be UV-stabilised?', answer: 'Yes, UV stabilisation packages are available for this ABS-PC blend. Please specify your outdoor exposure requirements when requesting a quotation.' },
// //     ],
// //     relatedProductSlugs: ['pp-homopolymer-compound', 'custom-masterbatch'],
// //     images: { card: '', hero: '', gallery: [] },
// //     featured: true,
// //     inStock: true,
// //     metaTitle: 'ABS-PC Engineering Blend — Engineering Polymers | Atharva Polymers',
// //     metaDescription: 'High-impact ABS-PC blend for automotive exterior and electronics. IATF 16949 certified. Manufactured in Pune, India.',
// //   },
// //   {
// //     id: '3',
// //     slug: 'custom-masterbatch',
// //     name: 'Custom Colour Masterbatch',
// //     category: 'specialty-compounds',
// //     tagline: 'Tailored colour concentrates for brand-matched consumer packaging and durable goods.',
// //     shortDescription: 'Bespoke colour masterbatch formulations for polyolefins and engineering resins with precise colour matching.',
// //     description: 'Custom-formulated colour masterbatches designed for exact brand colour matching in consumer packaging, caps and closures, and durable goods. Our in-house colour laboratory provides spectrophotometric matching and small-batch sampling for approval before production quantities.',
// //     industries: ['packaging', 'consumer-goods'],
// //     applications: [
// //       'Brand-colour packaging containers',
// //       'Caps and closures with precise colour requirements',
// //       'Consumer durable goods with custom colour specifications',
// //       'Appliance components requiring colour consistency',
// //     ],
// //     keyProperties: [
// //       { label: 'Carrier Resin', value: 'Polyolefin-based', unit: '' },
// //       { label: 'Colour Match', value: 'ΔE < 1.0', unit: '' },
// //       { label: 'Let-Down Ratio', value: '2–4', unit: '%' },
// //     ],
// //     technicalSpecs: [
// //       {
// //         title: 'General Properties',
// //         specs: [
// //           { property: 'Carrier Resin Type', value: 'LDPE / LLDPE / PP (customisable)', unit: '', standard: '' },
// //           { property: 'Pigment Loading', value: '20–60', unit: '%', standard: 'Per formulation' },
// //           { property: 'Let-Down Ratio', value: '2–4', unit: '%', standard: '' },
// //         ],
// //       },
// //     ],
// //     certifications: ['ISO 9001'],
// //     downloads: [
// //       { type: 'guide', title: 'Masterbatch Selection Guide', filename: 'masterbatch-guide.pdf', fileSizeLabel: 'PDF · 1.2 MB', href: '/assets/downloads/masterbatch-guide.pdf' },
// //     ],
// //     faq: [],
// //     relatedProductSlugs: ['pp-homopolymer-compound'],
// //     images: { card: '', hero: '', gallery: [] },
// //     featured: false,
// //     inStock: true,
// //     metaTitle: 'Custom Colour Masterbatch — Specialty Compounds | Atharva Polymers',
// //     metaDescription: 'Bespoke colour masterbatch for brand-matched packaging. Spectrophotometric colour matching. Manufactured in Pune.',
// //   },
// //   {
// //     id: '4',
// //     slug: 'hdpe-blow-moulding',
// //     name: 'HDPE Blow Moulding Grade',
// //     category: 'thermoplastics',
// //     tagline: 'High-molecular-weight HDPE for extrusion blow moulding of containers and automotive ducts.',
// //     shortDescription: 'HDPE grade optimised for blow moulding with excellent melt strength and environmental stress crack resistance.',
// //     description: 'A high-molecular-weight high-density polyethylene specifically formulated for extrusion blow moulding applications. Offers superior melt strength for parison control, excellent environmental stress crack resistance (ESCR), and consistent processing on single and dual-head blow moulding machines.',
// //     industries: ['packaging', 'automotive', 'industrial'],
// //     applications: [
// //       'Industrial chemical containers and jerry cans',
// //       'Automotive fluid reservoirs and ducts',
// //       'Large-volume storage drums',
// //       'Consumer packaging bottles',
// //     ],
// //     keyProperties: [
// //       { label: 'Melt Flow Index', value: '0.3', unit: 'g/10 min' },
// //       { label: 'Density', value: '0.953', unit: 'g/cm³' },
// //       { label: 'ESCR (100% Igepal)', value: '>300', unit: 'hours' },
// //     ],
// //     technicalSpecs: [
// //       {
// //         title: 'Physical Properties',
// //         specs: [
// //           { property: 'Density', value: '0.953', unit: 'g/cm³', standard: 'ISO 1183' },
// //           { property: 'Melt Flow Index (190°C/5kg)', value: '0.3', unit: 'g/10 min', standard: 'ISO 1133' },
// //         ],
// //       },
// //       {
// //         title: 'Mechanical Properties',
// //         specs: [
// //           { property: 'Tensile Strength at Yield', value: '26', unit: 'MPa', standard: 'ISO 527-2' },
// //           { property: 'Flexural Modulus', value: '1100', unit: 'MPa', standard: 'ISO 178' },
// //           { property: 'ESCR (100% Igepal, F50)', value: '>300', unit: 'hours', standard: 'ASTM D1693' },
// //         ],
// //       },
// //     ],
// //     certifications: ['IATF 16949', 'ISO 9001'],
// //     downloads: [
// //       { type: 'datasheet', title: 'Technical Data Sheet — HDPE Blow Moulding Grade', filename: 'hdpe-blow-tds.pdf', fileSizeLabel: 'PDF · 350 KB', href: '/assets/downloads/hdpe-blow-tds.pdf' },
// //     ],
// //     faq: [
// //       { question: 'Is this grade suitable for food-grade containers?', answer: 'Yes, this HDPE grade is available in food-contact-compliant formulations. Please specify your regulatory requirements when ordering.' },
// //     ],
// //     relatedProductSlugs: ['pp-homopolymer-compound', 'abs-pc-blend'],
// //     images: { card: '', hero: '', gallery: [] },
// //     featured: true,
// //     inStock: true,
// //     metaTitle: 'HDPE Blow Moulding Grade — Thermoplastics | Atharva Polymers',
// //     metaDescription: 'High-molecular-weight HDPE for blow moulding. Excellent ESCR. IATF 16949 certified. Pune, India.',
// //   },
// //   {
// //     id: '5',
// //     slug: 'pa6-gf30',
// //     name: 'PA6 GF30 Compound',
// //     category: 'engineering-polymers',
// //     tagline: '30% glass-fibre-reinforced polyamide 6 for high-strength structural automotive components.',
// //     shortDescription: 'Glass-fibre-reinforced PA6 offering excellent mechanical strength and thermal performance for under-hood applications.',
// //     description: 'A 30% glass-fibre-reinforced polyamide 6 (Nylon 6) compound engineered for high-strength structural applications in automotive under-hood and exterior environments. This grade provides exceptional tensile strength, heat resistance, and dimensional stability.',
// //     industries: ['automotive', 'industrial'],
// //     applications: [
// //       'Engine cover components and air intake manifolds',
// //       'Structural brackets and mounting systems',
// //       'Cooling fan assemblies',
// //       'Industrial machinery components',
// //     ],
// //     keyProperties: [
// //       { label: 'Density', value: '1.36', unit: 'g/cm³' },
// //       { label: 'Tensile Strength', value: '175', unit: 'MPa' },
// //       { label: 'HDT (1.8 MPa)', value: '205', unit: '°C' },
// //       { label: 'Glass Content', value: '30', unit: '%' },
// //     ],
// //     technicalSpecs: [
// //       {
// //         title: 'Physical Properties',
// //         specs: [
// //           { property: 'Density', value: '1.36', unit: 'g/cm³', standard: 'ISO 1183' },
// //           { property: 'Glass Fibre Content', value: '30', unit: '%', standard: 'ISO 3451' },
// //         ],
// //       },
// //       {
// //         title: 'Mechanical Properties',
// //         specs: [
// //           { property: 'Tensile Strength', value: '175', unit: 'MPa', standard: 'ISO 527-2' },
// //           { property: 'Flexural Modulus', value: '8500', unit: 'MPa', standard: 'ISO 178' },
// //           { property: 'Izod Impact (23°C)', value: '12', unit: 'kJ/m²', standard: 'ISO 180' },
// //         ],
// //       },
// //       {
// //         title: 'Thermal Properties',
// //         specs: [
// //           { property: 'HDT (1.8 MPa)', value: '205', unit: '°C', standard: 'ISO 75-2' },
// //         ],
// //       },
// //     ],
// //     certifications: ['IATF 16949', 'ISO 9001', 'ISO 14001'],
// //     downloads: [
// //       { type: 'datasheet', title: 'Technical Data Sheet — PA6 GF30', filename: 'pa6-gf30-tds.pdf', fileSizeLabel: 'PDF · 450 KB', href: '/assets/downloads/pa6-gf30-tds.pdf' },
// //     ],
// //     faq: [],
// //     relatedProductSlugs: ['abs-pc-blend', 'pp-homopolymer-compound'],
// //     images: { card: '', hero: '', gallery: [] },
// //     featured: false,
// //     inStock: true,
// //     metaTitle: 'PA6 GF30 Compound — Engineering Polymers | Atharva Polymers',
// //     metaDescription: '30% glass-fibre PA6 for structural automotive parts. IATF 16949 certified. Pune, India.',
// //   },
// //   {
// //     id: '6',
// //     slug: 'antistatic-pe',
// //     name: 'Antistatic PE Compound',
// //     category: 'specialty-compounds',
// //     tagline: 'Anti-static polyethylene for electronics packaging and ESD-sensitive industrial environments.',
// //     shortDescription: 'Specialty PE compound with permanent antistatic properties for electronics and hazardous-area packaging.',
// //     description: 'A specialty polyethylene compound with permanent antistatic additives designed for packaging applications in electronics manufacturing and ESD-sensitive environments. Surface resistivity is controlled to meet IEC 61340-5-1 requirements for ESD protective packaging.',
// //     industries: ['packaging', 'industrial', 'consumer-goods'],
// //     applications: [
// //       'Electronics component trays and packaging',
// //       'ESD-safe industrial containers',
// //       'Hazardous-area material handling',
// //       'Cleanroom-compatible packaging solutions',
// //     ],
// //     keyProperties: [
// //       { label: 'Surface Resistivity', value: '10⁶–10⁹', unit: 'Ω/sq' },
// //       { label: 'Density', value: '0.92', unit: 'g/cm³' },
// //       { label: 'Melt Flow Index', value: '4', unit: 'g/10 min' },
// //     ],
// //     technicalSpecs: [
// //       {
// //         title: 'Physical Properties',
// //         specs: [
// //           { property: 'Density', value: '0.92', unit: 'g/cm³', standard: 'ISO 1183' },
// //           { property: 'Melt Flow Index', value: '4', unit: 'g/10 min', standard: 'ISO 1133' },
// //         ],
// //       },
// //       {
// //         title: 'Electrical Properties',
// //         specs: [
// //           { property: 'Surface Resistivity', value: '10⁶–10⁹', unit: 'Ω/sq', standard: 'IEC 61340-2-3' },
// //           { property: 'Static Decay Time', value: '<2', unit: 'seconds', standard: 'IEC 61340-2-1' },
// //         ],
// //       },
// //     ],
// //     certifications: ['ISO 9001'],
// //     downloads: [],
// //     faq: [
// //       { question: 'Is the antistatic effect permanent or migratory?', answer: 'This compound uses a permanent (non-migratory) antistatic additive system. The antistatic properties remain effective throughout the product lifecycle and are not dependent on humidity.' },
// //     ],
// //     relatedProductSlugs: ['pp-homopolymer-compound', 'custom-masterbatch'],
// //     images: { card: '', hero: '', gallery: [] },
// //     featured: false,
// //     inStock: false,
// //     metaTitle: 'Antistatic PE Compound — Specialty Compounds | Atharva Polymers',
// //     metaDescription: 'Permanent antistatic PE for ESD packaging. IEC 61340 compliant. Pune, India.',
// //   },
// // ]

// // // Helper functions
// // export function getProductBySlug(slug: string): ProductDetail | undefined {
// //   return products.find((p) => p.slug === slug)
// // }

// // export function getProductsByCategory(category: string): ProductDetail[] {
// //   if (category === 'all') return products
// //   return products.filter((p) => p.category === category)
// // }

// // export function getRelatedProducts(slugs: string[]): ProductDetail[] {
// //   return slugs.map((s) => products.find((p) => p.slug === s)).filter(Boolean) as ProductDetail[]
// // }

// // src/lib/products-data.ts
// import type { Product } from '@/types/products'

// export const products: Product[] = [
//   // ─────────── Caps & Enclosures ───────────
//   {
//     id: '1',
//     slug: '28mm-cap',
//     name: '28 mm Cap',
//     industries: ['appliances', 'others'],
//     tagline: 'Standard white threaded cap for containers and closures.',
//     shortDescription: 'Injection‑moulded PP cap with precise threading.',
//     description:
//       'This 28 mm cap is a versatile closure used in packaging and container applications across appliance and industrial sectors.',
//     applications: ['Household containers', 'Industrial packaging'],
//     keyProperties: [
//       { label: 'Material', value: 'Polypropylene', unit: '' },
//       { label: 'Weight', value: '2.5', unit: 'g' },
//     ],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [
//       {
//         type: 'datasheet',
//         title: '28mm Cap Datasheet',
//         fileSizeLabel: 'PDF · 180 KB',
//         href: '#',
//       },
//     ],
//     faq: [
//       {
//         question: 'What colours are available?',
//         answer: 'Standard white. Custom colours available on request.',
//       },
//     ],
//     relatedProductSlugs: ['38mm-cap', '24-416-cap'],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '2',
//     slug: '38mm-cap',
//     name: '38 mm Cap',
//     industries: ['appliances', 'others'],
//     tagline: 'Widely used cap for industrial and consumer containers.',
//     shortDescription: 'Durable PP cap with consistent diameter and wall thickness.',
//     description:
//       '38 mm cap suitable for larger container openings, produced with high‑repeatability injection moulding.',
//     applications: ['Large household containers', 'Chemical drums'],
//     keyProperties: [
//       { label: 'Material', value: 'Polypropylene', unit: '' },
//       { label: 'Weight', value: '4.1', unit: 'g' },
//     ],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: ['28mm-cap'],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '3',
//     slug: '28mm-dish-cap',
//     name: '28 mm Dish Cap',
//     industries: ['appliances'],
//     tagline: 'Specialised cap with dish profile for unique designs.',
//     shortDescription: 'Low‑profile cap for cosmetic and speciality packaging.',
//     description:
//       'The dish cap provides a sleek, low‑profile closure often required in premium product packaging.',
//     applications: ['Cosmetic packaging', 'Speciality containers'],
//     keyProperties: [{ label: 'Material', value: 'PP', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '4',
//     slug: '24-416-cap',
//     name: '24/416 Cap',
//     industries: ['appliances', 'others'],
//     tagline: 'Tall ribbed cap for premium bottle closures.',
//     shortDescription: 'Ergonomic ribbed cap with standard 24/416 neck finish.',
//     description:
//       'Designed for beverage and personal care bottles, offering a secure seal and comfortable grip.',
//     applications: ['Water bottles', 'Personal care products'],
//     keyProperties: [
//       { label: 'Neck finish', value: '24/416', unit: '' },
//       { label: 'Height', value: '22', unit: 'mm' },
//     ],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [],
//     faq: [
//       {
//         question: 'Is food‑grade material available?',
//         answer: 'Yes, we can supply food‑grade PP on request.',
//       },
//     ],
//     relatedProductSlugs: ['28mm-cap'],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '5',
//     slug: '89mm-cap',
//     name: '89 mm Cap',
//     industries: ['others'],
//     tagline: 'Wide red cap for large‑format containers.',
//     shortDescription: 'High‑visibility industrial cap for bulk packaging.',
//     description:
//       'Engineered for durability and ease of handling on large industrial containers.',
//     applications: ['Bulk chemical drums', 'Large storage containers'],
//     keyProperties: [
//       { label: 'Material', value: 'PP', unit: '' },
//       { label: 'Diameter', value: '89', unit: 'mm' },
//     ],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '6',
//     slug: '67mm-cap',
//     name: '67 mm Cap',
//     industries: ['appliances', 'others'],
//     tagline: 'Red cap for medium‑sized containers.',
//     shortDescription: 'Reliable seal for jars and bottles up to 67 mm.',
//     description:
//       'High‑volume production with consistent colour and dimensions.',
//     applications: ['Jars', 'Industrial bottles'],
//     keyProperties: [{ label: 'Colour', value: 'Red', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '7',
//     slug: '70mm-cap',
//     name: '70 mm Cap',
//     industries: ['appliances', 'others'],
//     tagline: 'Red 70 mm cap for standard packaging.',
//     shortDescription: 'Widely used closure for food and chemical containers.',
//     description:
//       'Excellent sealing performance and chemical resistance.',
//     applications: ['Food containers', 'Chemical packaging'],
//     keyProperties: [{ label: 'Material', value: 'PP', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['ISO 9001'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: ['67mm-cap'],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },

//   // ─────────── Toro & Ditch Witch Parts (Automotive) ───────────
//   {
//     id: '8',
//     slug: 'seat-bottom',
//     name: 'Seat Bottom',
//     industries: ['automotive'],
//     tagline: 'Large structural seat for off‑road utility vehicles.',
//     shortDescription: 'Injection‑moulded seat base for Toro vehicles.',
//     description:
//       'Heavy‑duty part designed to withstand vibration and outdoor exposure. Exported to the United States.',
//     applications: ['Toro Workman', 'Ditch Witch vehicles'],
//     keyProperties: [
//       { label: 'Weight', value: '3.2', unit: 'kg' },
//       { label: 'Material', value: 'PP‑GF30', unit: '' },
//     ],
//     technicalSpecs: [
//       {
//         title: 'Mechanical',
//         specs: [
//           {
//             property: 'Tensile Strength',
//             value: '85',
//             unit: 'MPa',
//             standard: 'ISO 527',
//           },
//         ],
//       },
//     ],
//     certifications: ['IATF 16949'],
//     downloads: [
//       {
//         type: 'datasheet',
//         title: 'Seat Bottom TDS',
//         fileSizeLabel: 'PDF · 240 KB',
//         href: '#',
//       },
//     ],
//     faq: [],
//     relatedProductSlugs: ['control-mechanism'],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '9',
//     slug: 'control-mechanism',
//     name: 'Control Mechanism',
//     industries: ['automotive'],
//     tagline: 'Housing for throttle and drive controls.',
//     shortDescription: 'Complex structural component for vehicle systems.',
//     description:
//       'Requires tight tolerances and multiple mounting points. Manufactured to IATF 16949.',
//     applications: ['Throttle assemblies', 'Drive control units'],
//     keyProperties: [{ label: 'Material', value: 'PA6', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: ['seat-bottom'],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '10',
//     slug: 'vac-handle',
//     name: 'Vac Handle',
//     industries: ['automotive', 'others'],
//     tagline: 'Ergonomic grip handle for vacuum systems.',
//     shortDescription: 'Lightweight moulded handle for commercial vacuums.',
//     description:
//       'Designed for repetitive use in commercial environments.',
//     applications: ['Industrial vacuums', 'Vehicle cleaning systems'],
//     keyProperties: [{ label: 'Material', value: 'ABS', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '11',
//     slug: 'tee-fitting',
//     name: 'Tee Fitting',
//     industries: ['automotive'],
//     tagline: 'T‑shaped fluid connector for off‑road vehicles.',
//     shortDescription: 'Chemical‑resistant PP connector for fluid lines.',
//     description:
//       'Moulded with high chemical resistance and precise internal geometry.',
//     applications: ['Coolant lines', 'Hydraulic systems'],
//     keyProperties: [{ label: 'Material', value: 'PP', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },

//   // ─────────── Toro Optimus Parts (Automotive) ───────────
//   {
//     id: '12',
//     slug: 'button-stop',
//     name: 'Button Stop',
//     industries: ['automotive'],
//     tagline: 'Emergency stop button for autonomous mowers.',
//     shortDescription: 'Red safety button component for Toro Optimus.',
//     description: 'Critical safety component, exported to the US.',
//     applications: ['Autonomous lawnmower'],
//     keyProperties: [{ label: 'Colour', value: 'Red', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '13',
//     slug: 'shroud-body-lid',
//     name: 'Shroud Body Lid',
//     industries: ['automotive'],
//     tagline: 'Large grey cover for the Optimus chassis.',
//     shortDescription: 'Protective top cover for internal components.',
//     description:
//       'Precision‑moulded for perfect fit and weather resistance.',
//     applications: ['Lawnmower chassis'],
//     keyProperties: [{ label: 'Material', value: 'ABS‑PC', unit: '' }],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '14',
//     slug: 'panel-rear-charger',
//     name: 'Panel Rear Charger',
//     industries: ['automotive'],
//     tagline: 'Rear charging station panel.',
//     shortDescription: 'Enclosure for electrical contacts and mounting.',
//     description: 'Designed for outdoor durability and easy assembly.',
//     applications: ['Charging dock'],
//     keyProperties: [],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '15',
//     slug: 'panel-front-charger',
//     name: 'Panel Front Charger',
//     industries: ['automotive'],
//     tagline: 'Angled front panel for charging dock.',
//     shortDescription: 'Routes cables and protects connectors.',
//     description:
//       'Injection‑moulded with precise cut‑outs and mounting bosses.',
//     applications: ['Charging station'],
//     keyProperties: [],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '16',
//     slug: 'base-charger',
//     name: 'Base Charger',
//     industries: ['automotive'],
//     tagline: 'Mounting base for charging system.',
//     shortDescription: 'Structural platform for the charger assembly.',
//     description:
//       'Supports mechanical loads and provides electrical insulation.',
//     applications: ['Charging base'],
//     keyProperties: [],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '17',
//     slug: 'chassis-top-cover',
//     name: 'Chassis Top Cover',
//     industries: ['automotive'],
//     tagline: 'Upper shell for drivetrain and electronics.',
//     shortDescription: 'Complex grey structural cover.',
//     description:
//       'High‑quality surface finish and dimensional accuracy required.',
//     applications: ['Lawnmower body'],
//     keyProperties: [],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '18',
//     slug: 'shroud-rear-valance',
//     name: 'Shroud Rear Valance',
//     industries: ['automotive'],
//     tagline: 'Rear trim piece for the shroud.',
//     shortDescription: 'Snap‑fit finishing component.',
//     description:
//       'Moulded for assembly without additional fasteners.',
//     applications: ['Lawnmower exterior'],
//     keyProperties: [],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
//   {
//     id: '19',
//     slug: 'outer-bumper',
//     name: 'Outer Bumper',
//     industries: ['automotive'],
//     tagline: 'Curved impact‑absorbing bumper.',
//     shortDescription: 'Protects the mower body during operation.',
//     description:
//       'Made from high‑impact polymer to withstand repeated low‑speed impacts.',
//     applications: ['Lawnmower bumper'],
//     keyProperties: [],
//     technicalSpecs: [],
//     certifications: ['IATF 16949'],
//     downloads: [],
//     faq: [],
//     relatedProductSlugs: [],
//     images: { card: '', hero: '', gallery: [] },
//     inStock: true,
//   },
// ]

// // Helper functions
// export function getProductBySlug(slug: string): Product | undefined {
//   return products.find((p) => p.slug === slug)
// }

// export function getProductsByIndustry(industry: string): Product[] {
//   if (industry === 'all') return products
//   return products.filter((p) => p.industries.includes(industry))
// }

// src/lib/products-data.ts
import type { Product } from '@/types/products'

export const products: Product[] = [
  // ─────────── Caps & Enclosures ───────────
  {
    id: '1',
    slug: '28mm-cap',
    name: '28 mm Cap',
    industries: ['others'],
    tagline: 'Standard white threaded cap for containers and closures.',
    shortDescription: 'Injection‑moulded PP cap with precise threading.',
    description:
      'This 28 mm cap is a versatile closure used in packaging and container applications across appliance and industrial sectors.',
    applications: ['Household containers', 'Industrial packaging'],
    keyProperties: [
      { label: 'Material', value: 'Polypropylene', unit: '' },
      { label: 'Weight', value: '2.5', unit: 'g' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [
      {
        type: 'datasheet',
        title: '28mm Cap Datasheet',
        fileSizeLabel: 'PDF · 180 KB',
        href: '#',
      },
    ],
    faq: [
      {
        question: 'What colours are available?',
        answer: 'Standard white. Custom colours available on request.',
      },
    ],
    relatedProductSlugs: ['38mm-cap'],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '2',
    slug: '38mm-cap',
    name: '38 mm Cap',
    industries: ['others'],
    tagline: 'Widely used cap for industrial and consumer containers.',
    shortDescription: 'Durable PP cap with consistent diameter and wall thickness.',
    description:
      '38 mm cap suitable for larger container openings, produced with high‑repeatability injection moulding.',
    applications: ['Large household containers', 'Chemical drums'],
    keyProperties: [
      { label: 'Material', value: 'Polypropylene', unit: '' },
      { label: 'Weight', value: '4.1', unit: 'g' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: ['28mm-cap'],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '3',
    slug: '28mm-dish-cap',
    name: '28 mm Dish Cap',
    industries: ['others'],
    tagline: 'Specialised cap with dish profile for unique designs.',
    shortDescription: 'Low‑profile cap for cosmetic and speciality packaging.',
    description:
      'The dish cap provides a sleek, low‑profile closure often required in premium product packaging.',
    applications: ['Cosmetic packaging', 'Speciality containers'],
    keyProperties: [{ label: 'Material', value: 'PP', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/28mm_dish_cap.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '5',
    slug: '89mm-cap',
    name: '89 mm Cap',
    industries: ['others'],
    tagline: 'Wide red cap for large‑format containers.',
    shortDescription: 'High‑visibility industrial cap for bulk packaging.',
    description:
      'Engineered for durability and ease of handling on large industrial containers.',
    applications: ['Bulk chemical drums', 'Large storage containers'],
    keyProperties: [
      { label: 'Material', value: 'PP', unit: '' },
      { label: 'Diameter', value: '89', unit: 'mm' },
    ],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '6',
    slug: '67mm-cap',
    name: '67 mm Cap',
    industries: ['others'],
    tagline: 'Red cap for medium‑sized containers.',
    shortDescription: 'Reliable seal for jars and bottles up to 67 mm.',
    description:
      'High‑volume production with consistent colour and dimensions.',
    applications: ['Jars', 'Industrial bottles'],
    keyProperties: [{ label: 'Colour', value: 'Red', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Toro & Ditch Witch Parts (Automotive) ───────────
  {
    id: '8',
    slug: 'seat-bottom',
    name: 'Seat Bottom',
    industries: ['automotive'],
    tagline: 'Large structural seat for off‑road utility vehicles.',
    shortDescription: 'Injection‑moulded seat base for Toro vehicles.',
    description:
      'Heavy‑duty part designed to withstand vibration and outdoor exposure. Exported to the United States.',
    applications: ['Toro Workman', 'Ditch Witch vehicles'],
    keyProperties: [
      { label: 'Weight', value: '3.2', unit: 'kg' },
      { label: 'Material', value: 'PP‑GF30', unit: '' },
    ],
    technicalSpecs: [
      {
        title: 'Mechanical',
        specs: [
          {
            property: 'Tensile Strength',
            value: '85',
            unit: 'MPa',
            standard: 'ISO 527',
          },
        ],
      },
    ],
    certifications: ['IATF 16949'],
    downloads: [
      {
        type: 'datasheet',
        title: 'Seat Bottom TDS',
        fileSizeLabel: 'PDF · 240 KB',
        href: '#',
      },
    ],
    faq: [],
    relatedProductSlugs: ['control-mechanism'],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  // {
  //   id: '9',
  //   slug: 'control-mechanism',
  //   name: 'Control Mechanism',
  //   industries: ['automotive'],
  //   tagline: 'Housing for throttle and drive controls.',
  //   shortDescription: 'Complex structural component for vehicle systems.',
  //   description:
  //     'Requires tight tolerances and multiple mounting points. Manufactured to IATF 16949.',
  //   applications: ['Throttle assemblies', 'Drive control units'],
  //   keyProperties: [{ label: 'Material', value: 'PA6', unit: '' }],
  //   technicalSpecs: [],
  //   certifications: ['IATF 16949'],
  //   downloads: [],
  //   faq: [],
  //   relatedProductSlugs: ['seat-bottom'],
  //   images: { card: '', hero: '', gallery: [] },
  //   inStock: true,
  // },
  {
    id: '10',
    slug: 'vac-handle',
    name: 'Vac Handle',
    industries: ['automotive', 'others'],
    tagline: 'Ergonomic grip handle for vacuum systems.',
    shortDescription: 'Lightweight moulded handle for commercial vacuums.',
    description:
      'Designed for repetitive use in commercial environments.',
    applications: ['Industrial vacuums', 'Vehicle cleaning systems'],
    keyProperties: [{ label: 'Material', value: 'ABS', unit: '' }],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Toro Optimus Parts (Automotive) ───────────
  {
    id: '12',
    slug: 'button-stop',
    name: 'Button Stop',
    industries: ['automotive'],
    tagline: 'Emergency stop button for autonomous mowers.',
    shortDescription: 'Red safety button component for Toro Optimus.',
    description: 'Critical safety component, exported to the US.',
    applications: ['Autonomous lawnmower'],
    keyProperties: [{ label: 'Colour', value: 'Red', unit: '' }],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '13',
    slug: 'shroud-body-lid',
    name: 'Shroud Body Lid',
    industries: ['automotive'],
    tagline: 'Large grey cover for the Optimus chassis.',
    shortDescription: 'Protective top cover for internal components.',
    description:
      'Precision‑moulded for perfect fit and weather resistance.',
    applications: ['Lawnmower chassis'],
    keyProperties: [{ label: 'Material', value: 'ABS‑PC', unit: '' }],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: 'assets/products/shroud_body_lid.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '14',
    slug: 'panel-rear-charger',
    name: 'Panel Rear Charger',
    industries: ['automotive'],
    tagline: 'Rear charging station panel.',
    shortDescription: 'Enclosure for electrical contacts and mounting.',
    description: 'Designed for outdoor durability and easy assembly.',
    applications: ['Charging dock'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '15',
    slug: 'panel-front-charger',
    name: 'Panel Front Charger',
    industries: ['automotive'],
    tagline: 'Angled front panel for charging dock.',
    shortDescription: 'Routes cables and protects connectors.',
    description:
      'Injection‑moulded with precise cut‑outs and mounting bosses.',
    applications: ['Charging station'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '16',
    slug: 'base-charger',
    name: 'Base Charger',
    industries: ['automotive'],
    tagline: 'Mounting base for charging system.',
    shortDescription: 'Structural platform for the charger assembly.',
    description:
      'Supports mechanical loads and provides electrical insulation.',
    applications: ['Charging base'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '17',
    slug: 'chassis-top-cover',
    name: 'Chassis Top Cover',
    industries: ['automotive'],
    tagline: 'Upper shell for drivetrain and electronics.',
    shortDescription: 'Complex grey structural cover.',
    description:
      'High‑quality surface finish and dimensional accuracy required.',
    applications: ['Lawnmower body'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
  id: '18',
  slug: 'jl-side-cover',
  name: 'JL Side Cover',
  industries: ['automotive'],
  tagline: 'Durable side cover panel for vehicle exteriors.',
  shortDescription: 'Precision‑moulded side cover for automotive body applications.',
  description:
    'Designed for easy assembly and a clean, finished look, this JL side cover provides durable protection for automotive exterior body panels. Manufactured to IATF 16949 standards.',
  applications: ['Automotive exterior', 'Vehicle body panels'],
  keyProperties: [],
  technicalSpecs: [],
  certifications: ['IATF 16949'],
  downloads: [],
  faq: [],
  relatedProductSlugs: [],
  images: { card: '/assets/products/jl_side_cover.png', hero: '', gallery: [] },
  inStock: true,
},
  {
    id: '19',
    slug: 'outer-bumper',
    name: 'Outer Bumper',
    industries: ['automotive'],
    tagline: 'Curved impact‑absorbing bumper.',
    shortDescription: 'Protects the mower body during operation.',
    description:
      'Made from high‑impact polymer to withstand repeated low‑speed impacts.',
    applications: ['Lawnmower bumper'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['IATF 16949'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Furniture ───────────
  {
    id: '20',
    slug: 'star-base',
    name: 'Star Base',
    industries: ['furniture'],
    tagline: 'Five‑star swivel base for office chairs.',
    shortDescription: 'Sturdy injection‑moulded star base.',
    description:
      'Load‑bearing base component compatible with standard chair mechanisms.',
    applications: ['Office chairs', 'Task seating'],
    keyProperties: [{ label: 'Material', value: 'PP‑GF', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/star-base.jpeg', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '21',
    slug: 'shell-membrane',
    name: 'Shell Membrane',
    industries: ['furniture'],
    tagline: 'Flexible seat shell support.',
    shortDescription: 'Ergonomic membrane for seat comfort.',
    description:
      'Injection‑moulded component providing tensioned support in ergonomic chairs.',
    applications: ['Ergonomic seating', 'Mesh chairs'],
    keyProperties: [{ label: 'Material', value: 'TPE', unit: '' }],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/shell_membrane.jpeg', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '22',
    slug: 'arm-rest',
    name: 'Arm Rest',
    industries: ['furniture'],
    tagline: 'Adjustable arm support for chairs.',
    shortDescription: 'Moulded armrest with soft‑touch surface.',
    description:
      'Available in various colours and surface finishes for comfort and durability.',
    applications: ['Office chairs', 'Lounge seating'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  // {
  //   id: '23',
  //   slug: 'arm-pad-holder',
  //   name: 'Arm Pad Holder',
  //   industries: ['furniture'],
  //   tagline: 'Internal bracket for arm pads.',
  //   shortDescription: 'Structural holder for armrest cushion.',
  //   description:
  //     'Precision‑moulded to securely attach arm pads to the armrest mechanism.',
  //   applications: ['Chair arm assembly'],
  //   keyProperties: [],
  //   technicalSpecs: [],
  //   certifications: ['ISO 9001'],
  //   downloads: [],
  //   faq: [],
  //   relatedProductSlugs: [],
  //   images: { card: '', hero: '', gallery: [] },
  //   inStock: true,
  // },
  {
    id: '24',
    slug: 'outer-sleve',
    name: 'Outer Sleve',
    industries: ['furniture'],
    tagline: 'Decorative outer cover for gas lift.',
    shortDescription: 'Telescopic cover tube.',
    description:
      'Used to conceal the height adjustment cylinder in office chairs.',
    applications: ['Chair gas lift cover'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '25',
    slug: 'height-adjuster',
    name: 'Height Adjuster',
    industries: ['furniture'],
    tagline: 'Actuator mechanism for seat height.',
    shortDescription: 'Lever or paddle for gas lift control.',
    description:
      'Ergonomically designed for easy reach and operation.',
    applications: ['Office chairs', 'Bar stools'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '26',
    slug: 'sr-jr-back-rest',
    name: 'Sr./Jr. Back Rest',
    industries: ['furniture'],
    tagline: 'Backrest frames for different chair sizes.',
    shortDescription: 'Sturdy moulded frame for back cushion mounting.',
    description:
      'Senior and Junior variants accommodate different chair dimensions.',
    applications: ['Office chairs', 'Task seating'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '27',
    slug: 'sr-jr-back-cover',
    name: 'Sr./Jr. Back Cover',
    industries: ['furniture'],
    tagline: 'Rear shell cover for backrest.',
    shortDescription: 'Aesthetic cover panel.',
    description:
      'Snaps onto the backrest frame to provide a finished look.',
    applications: ['Chair exterior'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '28',
    slug: 'cub-chair',
    name: 'Cub Chair',
    industries: ['furniture'],
    tagline: 'Compact moulded chair shell.',
    shortDescription: 'Single‑piece chair for educational and home use.',
    description:
      'Lightweight and stackable design, suitable for kids and casual seating.',
    applications: ['Schools', 'Home office'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '', hero: '', gallery: [] },
    inStock: true,
  },

  // ─────────── Appliances (new additions) ───────────
  {
    id: '29',
    slug: 'base-stand',
    name: 'Base Stand',
    industries: ['appliances'],
    tagline: 'Support stand for household appliances.',
    shortDescription: 'Stable base for mixers, grinders, and similar devices.',
    description:
      'Injection‑moulded with vibration damping and non‑slip feet.',
    applications: ['Kitchen appliances', 'Home electronics'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/base_stand.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '30',
    slug: 'tmbm-duct-cover',
    name: 'TMBM Duct Cover',
    industries: ['appliances'],
    tagline: 'Cover panel for appliance ductwork.',
    shortDescription: 'Thermoplastic duct cover for air management.',
    description:
      'Used in HVAC and domestic appliances to direct airflow safely.',
    applications: ['Air conditioners', 'Dryers'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/tmbm_duct_cover.png', hero: '', gallery: [] },
    inStock: true,
  },
  {
    id: '31',
    slug: 'veg-box',
    name: 'Veg Box',
    industries: ['appliances'],
    tagline: 'Refrigerator vegetable crisper tray.',
    shortDescription: 'Clear or opaque storage compartment for produce.',
    description:
      'Designed to maintain optimal humidity and easy cleaning.',
    applications: ['Refrigerators', 'Coolers'],
    keyProperties: [],
    technicalSpecs: [],
    certifications: ['ISO 9001'],
    downloads: [],
    faq: [],
    relatedProductSlugs: [],
    images: { card: '/assets/products/veg_box.jpeg', hero: '', gallery: [] },
    inStock: true,
  },
  {
  id: '8',
  slug: 'seat-top',
  name: 'Seat Top',
  industries: ['automotive'],
  tagline: 'Large structural seat top for off‑road utility vehicles.',
  shortDescription: 'Injection‑moulded seat top for Toro vehicles.',
  description:
    'Heavy‑duty seat top designed to withstand vibration and outdoor exposure. Exported to the United States.',
  applications: ['Toro Workman', 'Ditch Witch vehicles'],
  keyProperties: [
    { label: 'Weight', value: '3.2', unit: 'kg' },
    { label: 'Material', value: 'PP‑GF30', unit: '' },
  ],
  technicalSpecs: [
    {
      title: 'Mechanical',
      specs: [
        {
          property: 'Tensile Strength',
          value: '85',
          unit: 'MPa',
          standard: 'ISO 527',
        },
      ],
    },
  ],
  certifications: ['IATF 16949'],
  downloads: [
    {
      type: 'datasheet',
      title: 'Seat Top TDS',
      fileSizeLabel: 'PDF · 240 KB',
      href: '#',
    },
  ],
  faq: [],
  relatedProductSlugs: ['control-mechanism'],
  images: { card: '/assets/products/seat_top.png', hero: '', gallery: [] },
  inStock: true,
},
]

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByIndustry(industry: string): Product[] {
  if (industry === 'all') return products
  return products.filter((p) => p.industries.includes(industry))
}